run_type = "staged_learning"
device = "cpu"
# device = "cuda:0"   # uncomment if GPU available
tb_logdir = "tb_RL_ic50_epoch4"
json_out_config = "rl_saponin_ic50_epoch4.json"

[parameters]
prior_file = "../../priors/saponin_prior_46k_reg_epoch4.prior"
agent_file = "../../priors/saponin_prior_46k_reg_epoch4.prior"
summary_csv_prefix = "rl_saponin_ic50_epoch4"
use_checkpoint = false
purge_memories = false
smiles_file = ""
sample_strategy = "multinomial"
distance_threshold = 100
batch_size = 64
randomize_smiles = true
isomeric_smiles = false
temperature = 1.0

[learning_strategy]
type = "dap"
sigma = 128
rate = 0.0001

[[stage]]
max_steps = 200
max_score = 0.8
chkpt_file = "../../priors/saponin_ic50_rl_epoch4.chkpt"
termination = "simple"
min_steps = 50

[stage.scoring]
type = "geometric_mean"

[[stage.scoring.component]]
[stage.scoring.component.external_process]
[[stage.scoring.component.external_process.endpoint]]
name = "Predicted IC50"
weight = 1.0
params.executable = "python"
params.args = "../../scripts/ic50_scorer.py"
params.property = "predictions"

[stage.scoring.component.external_process.endpoint.transform]
type = "reverse_sigmoid"
high = 5.0
low = 0.0
k = 0.5