run_type = "sampling"

[parameters]
model_file = "../../priors/reinvent_pubchem.prior"
num_smiles = 10000
output_file = "../../samples/ic50_generic_prior_samples.csv"
unique_molecules = true
randomize_smiles = true
temperature = 1.0
isomeric_smiles = false