run_type = "sampling"

[parameters]
model_file = "../../priors/saponin_ic50_rl_epoch4.chkpt"
num_smiles = 2000
output_file = "../../samples/rl_agent_samples.csv"
unique_molecules = true
randomize_smiles = true
temperature = 1.0
isomeric_smiles = false