run_type = "sampling"
device = "cpu"
tb_logdir = "tb_sampling_rl_epoch1"
json_out_config = "sampling_rl_epoch1.json"

[parameters]
model_file = "../../priors/saponin_prior_46k_reg_epoch1.prior"
output_file = "../../samples/rl_epoch1_samples.csv"
sample_strategy = "multinomial"
batch_size = 128
num_smiles = 10000
unique_molecules = true
randomize_smiles = true
isomeric_smiles = false
temperature = 1.0