run_type = "transfer_learning"
tb_logdir = "tb_TL_saponin_block2_pure"
json_out_config = "transfer_learning_saponin_block2_pure.json"

[parameters]
num_epochs = 1
save_every_n_epochs = 1
batch_size = 16
num_refs = 0

input_model_file  = "../priors/saponin_prior_block1.prior"
smiles_file       = "../data/saponin_train_46k_block2.smi"
output_model_file = "../priors/saponin_prior_block2.prior"