run_type = "transfer_learning"
tb_logdir = "tb_TL_saponin_46k_e3b2_reg"
json_out_config = "transfer_learning_saponin_46k_e3b2_reg.json"

[parameters]
num_epochs = 1
save_every_n_epochs = 1
batch_size = 16
num_refs = 16
sample_batch_size = 128

input_model_file  = "../priors/saponin_prior_46k_tmp_e3b1.prior"
smiles_file       = "../data/saponin_train_46k_block2.smi"
output_model_file = "../priors/saponin_prior_46k_tmp_e3b2.prior"

[parameters.pairs]
type = "tanimoto"
lower_threshold = 0.4
upper_threshold = 0.8
min_cardinality = 1
max_cardinality = 199