run_type = "transfer_learning"
tb_logdir = "tb_TL_saponin_3k_hermes"
json_out_config = "transfer_learning_saponin_3k_hermes.json"

[parameters]
num_epochs = 1
save_every_n_epochs = 1
batch_size = 16
num_refs = 0

input_model_file = "../priors/reinvent_pubchem.prior"
smiles_file = "../data/saponin_train_3k.smi"
output_model_file = "../priors/saponin_prior_3k_hermes_dryrun.prior"
